version: "3.8"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    # container_name: rd01
    ports:
      - 6379:6379

  celery:
    build: .
    volumes:
      - .:/src
    # container_name: cl01
    command: celery -A shap_django worker #-l info
    links:
      - redis
